#!/bin/bash
# ======================================================================
# This file was automatically generated by SbatchMan.
# Do not edit this file manually (unless you know what you are doing).
# ======================================================================

# Local execution script
echo "start_timestamp: '$(date +%Y%m%d_%H%M%S.%N)'" >> "{EXP_DIR}/metadata.yaml"


# Change to the submission directory
cd "{CWD}"

# Update job_id in metadata.yaml
perl -i -pe"s/job_id: [0-9]*/job_id: $$/" "{EXP_DIR}/metadata.yaml"

# Update status to RUNNING
if [ -f "{EXP_DIR}/metadata.yaml" ]; then
 perl -i -pe's/status: .*/status: RUNNING/' {EXP_DIR}/metadata.yaml
fi

# (Optional) Preprocess command
{PREPROCESS}

# User command
{CMD}
EXIT_CODE=$?

# Update status to COMPLETED or FAILED
if [ -f "{EXP_DIR}/metadata.yaml" ]; then
  if [ $EXIT_CODE -eq 0 ]; then
    perl -i -pe's/status: .*/status: COMPLETED/' {EXP_DIR}/metadata.yaml
  else
    perl -i -pe's/status: .*/status: FAILED/' {EXP_DIR}/metadata.yaml
  fi
  perl -i -pe"s/exitcode: .*/exitcode: $EXIT_CODE/" {EXP_DIR}/metadata.yaml
fi

# (Optional) Postprocess command
{POSTPROCESS}

echo "end_timestamp: '$(date +%Y%m%d_%H%M%S.%N)'" >> "{EXP_DIR}/metadata.yaml"

exit $EXIT_CODE